import 'package:flutter/material.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'app_name': 'StoryVerse',
      'welcome': 'Welcome to StoryVerse',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'phone': 'Phone Number',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'already_have_account': 'Already have an account?',
      'sign_up': 'Sign Up',
      'sign_in': 'Sign In',
      'google_login': 'Login with Google',
      'phone_login': 'Login with Phone',
      'guest_login': 'Continue as Guest',
      'home': 'Home',
      'search': 'Search',
      'categories': 'Categories',
      'profile': 'Profile',
      'library': 'Library',
      'featured_stories': 'Featured Stories',
      'trending_stories': 'Trending Stories',
      'popular_stories': 'Popular Stories',
      'latest_stories': 'Latest Stories',
      'recommended_stories': 'Recommended for You',
      'continue_reading': 'Continue Reading',
      'popular_authors': 'Popular Authors',
      'daily_picks': 'Daily Picks',
      'story_details': 'Story Details',
      'read': 'Read',
      'bookmark': 'Bookmark',
      'share': 'Share',
      'download': 'Download',
      'reviews': 'Reviews',
      'comments': 'Comments',
      'related_stories': 'Related Stories',
      'chapters': 'Chapters',
      'rating': 'Rating',
      'views': 'Views',
      'likes': 'Likes',
      'description': 'Description',
      'author': 'Author',
      'language': 'Language',
      'category': 'Category',
      'tags': 'Tags',
      'upload_cover': 'Upload Cover',
      'story_title': 'Story Title',
      'publish': 'Publish',
      'draft': 'Draft',
      'save_draft': 'Save Draft',
      'preview': 'Preview',
      'settings': 'Settings',
      'dark_theme': 'Dark Theme',
      'light_theme': 'Light Theme',
      'notifications': 'Notifications',
      'privacy': 'Privacy',
      'delete_account': 'Delete Account',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'followers': 'Followers',
      'following': 'Following',
      'bookmarks': 'Bookmarks',
      'downloads': 'Downloads',
      'history': 'History',
      'achievements': 'Achievements',
      'premium': 'Premium',
      'premium_membership': 'Premium Membership',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'lifetime': 'Lifetime',
      'wallet': 'Wallet',
      'coins': 'Coins',
      'rewards': 'Rewards',
      'transactions': 'Transactions',
      'recharge': 'Recharge',
      'withdraw': 'Withdraw',
      'referral_bonus': 'Referral Bonus',
      'invite_friends': 'Invite Friends',
      'watch_ads': 'Watch Ads',
      'reading_streak': 'Reading Streak',
      'badges': 'Badges',
      'leaderboard': 'Leaderboard',
      'daily_challenges': 'Daily Challenges',
      'notifications': 'Notifications',
      'new_chapter': 'New Chapter',
      'community': 'Community',
      'replies': 'Replies',
      'report': 'Report',
      'story_upload': 'Upload Story',
      'author_dashboard': 'Author Dashboard',
      'rich_text_editor': 'Text Editor',
      'bold': 'Bold',
      'italic': 'Italic',
      'underline': 'Underline',
      'headings': 'Headings',
      'images': 'Images',
      'audio_story': 'Audio Story',
      'play': 'Play',
      'pause': 'Pause',
      'resume': 'Resume',
      'playback_speed': 'Playback Speed',
      'sleep_timer': 'Sleep Timer',
      'offline_reading': 'Offline Reading',
      'highlight_text': 'Highlight Text',
      'reading_time': 'Reading Time',
      'page_animation': 'Page Animation',
      'fullscreen': 'Fullscreen',
      'brightness': 'Brightness',
      'auto_scroll': 'Auto Scroll',
      'line_height': 'Line Height',
      'font_size': 'Font Size',
      'sepia_theme': 'Sepia Theme',
      'admin_panel': 'Admin Panel',
      'manage_users': 'Manage Users',
      'manage_stories': 'Manage Stories',
      'manage_authors': 'Manage Authors',
      'manage_reports': 'Manage Reports',
      'manage_categories': 'Manage Categories',
      'analytics': 'Analytics',
      'revenue': 'Revenue',
      'approve_stories': 'Approve Stories',
      'reject_stories': 'Reject Stories',
      'ban_users': 'Ban Users',
      'romance': 'Romance',
      'love': 'Love',
      'horror': 'Horror',
      'mystery': 'Mystery',
      'fantasy': 'Fantasy',
      'adventure': 'Adventure',
      'action': 'Action',
      'comedy': 'Comedy',
      'thriller': 'Thriller',
      'historical': 'Historical',
      'science_fiction': 'Science Fiction',
      'kids': 'Kids',
      'motivation': 'Motivation',
      'crime': 'Crime',
      'biography': 'Biography',
      'poetry': 'Poetry',
      'success': 'Success',
      'error': 'Error',
      'loading': 'Loading...',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'apply': 'Apply',
      'filter': 'Filter',
      'sort': 'Sort',
      'clear_all': 'Clear All',
      'more': 'More',
      'view_all': 'View All',
      'no_data': 'No Data',
      'no_results': 'No Results Found',
      'something_went_wrong': 'Something went wrong',
      'try_again': 'Try Again',
      'welcome_back': 'Welcome Back!',
      'create_account': 'Create Your Account',
      'verify_email': 'Verify Email',
      'verification_code': 'Verification Code',
      'send_code': 'Send Code',
      'resend_code': 'Resend Code',
      'reset_password': 'Reset Password',
      'new_password': 'New Password',
      'password_reset_success': 'Password Reset Successfully',
      'continue': 'Continue',
      'next': 'Next',
      'back': 'Back',
      'skip': 'Skip',
      'finish': 'Finish',
      'explore': 'Explore',
    },
    'hi': {
      'app_name': 'StoryVerse',
      'welcome': 'StoryVerse में स्वागत है',
      'login': 'लॉगिन करें',
      'register': 'पंजीकरण करें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'phone': 'फोन नंबर',
      'forgot_password': 'पासवर्ड भूल गए?',
      'dont_have_account': 'खाता नहीं है?',
      'already_have_account': 'पहले से खाता है?',
      'sign_up': 'साइन अप करें',
      'sign_in': 'साइन इन करें',
      'google_login': 'Google के साथ लॉगिन करें',
      'phone_login': 'फोन के साथ लॉगिन करें',
      'guest_login': 'अतिथि के रूप में जारी रखें',
      'home': 'होम',
      'search': 'खोज',
      'categories': 'श्रेणियाँ',
      'profile': 'प्रोफाइल',
      'library': 'पुस्तकालय',
      'featured_stories': 'विशेष कहानियाँ',
      'trending_stories': 'ट्रेंडिंग कहानियाँ',
      'popular_stories': 'लोकप्रिय कहानियाँ',
      'latest_stories': 'नवीनतम कहानियाँ',
      'recommended_stories': 'आपके लिए अनुशंसित',
      'continue_reading': 'पढ़ना जारी रखें',
      'popular_authors': 'लोकप्रिय लेखक',
      'daily_picks': 'दैनिक पिक्स',
      'story_details': 'कहानी विवरण',
      'read': 'पढ़ें',
      'bookmark': 'बुकमार्क',
      'share': 'साझा करें',
      'download': 'डाउनलोड करें',
      'reviews': 'समीक्षाएं',
      'comments': 'टिप्पणियाँ',
      'related_stories': 'संबंधित कहानियाँ',
      'chapters': 'अध्याय',
      'rating': 'रेटिंग',
      'views': 'दृश्य',
      'likes': 'पसंद',
      'description': 'विवरण',
      'author': 'लेखक',
      'language': 'भाषा',
      'category': 'श्रेणी',
      'tags': 'टैग',
      'upload_cover': 'कवर अपलोड करें',
      'story_title': 'कहानी का शीर्षक',
      'publish': 'प्रकाशित करें',
      'draft': 'ड्राफ्ट',
      'save_draft': 'ड्राफ्ट सहेजें',
      'preview': 'पूर्वावलोकन',
      'settings': 'सेटिंग्स',
      'dark_theme': 'डार्क थीम',
      'light_theme': 'लाइट थीम',
      'notifications': 'सूचनाएं',
      'privacy': 'गोपनीयता',
      'delete_account': 'खाता हटाएं',
      'logout': 'लॉगआउट करें',
      'edit_profile': 'प्रोफाइल संपादित करें',
      'followers': 'अनुयायी',
      'following': 'अनुसरण कर रहे हैं',
      'bookmarks': 'बुकमार्क',
      'downloads': 'डाउनलोड',
      'history': 'इतिहास',
      'achievements': 'उपलब्धियाँ',
      'premium': 'प्रीमियम',
      'premium_membership': 'प्रीमियम सदस्यता',
      'monthly': 'मासिक',
      'yearly': 'वार्षिक',
      'lifetime': 'आजीवन',
      'wallet': 'वॉलेट',
      'coins': 'सिक्के',
      'rewards': 'पुरस्कार',
      'transactions': 'लेनदेन',
      'recharge': 'रीचार्ज करें',
      'withdraw': 'निकालें',
      'referral_bonus': 'रेफरल बोनस',
      'invite_friends': 'दोस्तों को आमंत्रित करें',
      'watch_ads': 'विज्ञापन देखें',
      'reading_streak': 'पढ़ने की श्रृंखला',
      'badges': 'बैज',
      'leaderboard': 'लीडरबोर्ड',
      'daily_challenges': 'दैनिक चुनौतियाँ',
      'community': 'समुदाय',
      'replies': 'उत्तर',
      'report': 'रिपोर्ट करें',
      'story_upload': 'कहानी अपलोड करें',
      'author_dashboard': 'लेखक डैशबोर्ड',
      'rich_text_editor': 'पाठ संपादक',
      'bold': 'बोल्ड',
      'italic': 'तिरछा',
      'underline': 'रेखांकित',
      'headings': 'शीर्षक',
      'images': 'छवियाँ',
      'audio_story': 'ऑडियो कहानी',
      'play': 'चलाएँ',
      'pause': 'रोकें',
      'resume': 'फिर से शुरू करें',
      'playback_speed': 'चलाने की गति',
      'sleep_timer': 'नींद टाइमर',
      'offline_reading': 'ऑफलाइन पढ़ना',
      'highlight_text': 'पाठ को हाइलाइट करें',
      'reading_time': 'पढ़ने का समय',
      'page_animation': 'पृष्ठ एनिमेशन',
      'fullscreen': 'पूर्ण स्क्रीन',
      'brightness': 'चमक',
      'auto_scroll': 'स्वचालित स्क्रॉल',
      'line_height': 'पंक्ति ऊंचाई',
      'font_size': 'फॉन्ट का आकार',
      'sepia_theme': 'सेपिया थीम',
      'admin_panel': 'व्यवस्थापक पैनल',
      'manage_users': 'उपयोगकर्ताओं को प्रबंधित करें',
      'manage_stories': 'कहानियों को प्रबंधित करें',
      'manage_authors': 'लेखकों को प्रबंधित करें',
      'manage_reports': 'रिपोर्ट प्रबंधित करें',
      'manage_categories': 'श्रेणियों को प्रबंधित करें',
      'analytics': 'विश्लेषण',
      'revenue': 'राजस्व',
      'approve_stories': 'कहानियों को मंजूरी दें',
      'reject_stories': 'कहानियों को अस्वीकार करें',
      'ban_users': 'उपयोगकर्ताओं पर प्रतिबंध लगाएं',
      'romance': 'रोमांस',
      'love': 'प्रेम',
      'horror': 'भयानक',
      'mystery': 'रहस्य',
      'fantasy': 'कल्पना',
      'adventure': 'रोमांच',
      'action': 'एक्शन',
      'comedy': 'हास्य',
      'thriller': 'रोमांचक',
      'historical': 'ऐतिहासिक',
      'science_fiction': 'विज्ञान कल्पना',
      'kids': 'बच्चे',
      'motivation': 'प्रेरणा',
      'crime': 'अपराध',
      'biography': 'जीवनी',
      'poetry': 'कविता',
      'success': 'सफल',
      'error': 'त्रुटि',
      'loading': 'लोड हो रहा है...',
      'retry': 'फिर से प्रयास करें',
      'cancel': 'रद्द करें',
      'ok': 'ठीक है',
      'yes': 'हाँ',
      'no': 'नहीं',
      'apply': 'लागू करें',
      'filter': 'फ़िल्टर',
      'sort': 'क्रमबद्ध करें',
      'clear_all': 'सभी साफ़ करें',
      'more': 'अधिक',
      'view_all': 'सभी देखें',
      'no_data': 'कोई डेटा नहीं',
      'no_results': 'कोई परिणाम नहीं मिला',
      'something_went_wrong': 'कुछ गलत हुआ',
      'try_again': 'फिर से कोशिश करें',
      'welcome_back': 'वापसी पर स्वागत है!',
      'create_account': 'अपना खाता बनाएँ',
      'verify_email': 'ईमेल सत्यापित करें',
      'verification_code': 'सत्यापन कोड',
      'send_code': 'कोड भेजें',
      'resend_code': 'कोड फिर से भेजें',
      'reset_password': 'पासवर्ड रीसेट करें',
      'new_password': 'नया पासवर्ड',
      'password_reset_success': 'पासवर्ड सफलतापूर्वक रीसेट हुआ',
      'continue': 'जारी रखें',
      'next': 'अगला',
      'back': 'पीछे',
      'skip': 'छोड़ें',
      'finish': 'समाप्त करें',
      'explore': 'खोजें',
    },
  };

  static String translate(String key, Locale locale) {
    final languageCode = locale.languageCode;
    if (_localizedStrings.containsKey(languageCode)) {
      return _localizedStrings[languageCode]?[key] ?? key;
    }
    return _localizedStrings['en']?[key] ?? key;
  }
}
